USE QLBongDa
GO

CREATE TABLE QUOCGIA (
	MAQG VARCHAR(5) PRIMARY KEY, 
	TENQG NVARCHAR(60) NOT NULL 
)
GO

CREATE TABLE TINH (
	MATINH VARCHAR(5) PRIMARY KEY,
	TENTINH NVARCHAR(100) NOT NULL, 
)
GO

CREATE TABLE SANVD (
	MASAN VARCHAR(5) PRIMARY KEY,
	TENSAN NVARCHAR(100) NOT NULL, 
	DIACHI NVARCHAR(200)
)
GO

--- --- 

CREATE TABLE CAULACBO(
	MACLB VARCHAR(5) PRIMARY KEY,
	TENCLB NVARCHAR(100) NOT NULL,
	MASAN VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES SANVD(MASAN), 
	MATINH VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES TINH(MATINH),
)
GO 

CREATE TABLE HUANLUYENVIEN (
	MAHLV VARCHAR(5) PRIMARY KEY,
	TENHLV NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	DIENTHOAI NVARCHAR(20),
	MAQG VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES QUOCGIA(MAQG)
)
GO

CREATE TABLE CAUTHU (
	MACT NUMERIC IDENTITY(1, 1) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	VITRI NVARCHAR(20) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MACLB VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES CAULACBO(MACLB),
	MAQG VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES QUOCGIA(MAQG),
	SO INT NOT NULL
)
GO

CREATE TABLE HLV_CLB (
	MAHLV VARCHAR(5),
	MACLB VARCHAR(5),
	VAITRO NVARCHAR(100) NOT NULL,
	PRIMARY KEY (MAHLV, MACLB), 
	FOREIGN kEY (MAHLV) REFERENCES HUANLUYENVIEN(MAHLV),
	FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB)
)
GO


CREATE TABLE TRANDAU (
    MATRAN NUMERIC IDENTITY(1,1) PRIMARY KEY,
    NAM INT NOT NULL,
    VONG INT NOT NULL,
    NGAYTD DATETIME NOT NULL,
    MACLB1 VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES CAULACBO(MACLB),
    MACLB2 VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES CAULACBO(MACLB),
    MASAN VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES SANVD(MASAN),
    KETQUA VARCHAR(5) NOT NULL
)
GO

CREATE TABLE BANGXH (
    MACLB VARCHAR(5),
    NAM INT,
    VONG INT,
    SOTRAN INT NOT NULL,
    THANG INT NOT NULL,
    HOA INT NOT NULL,
    THUA INT NOT NULL,
    HIEUSO VARCHAR(5) NOT NULL,
    DIEM INT NOT NULL,
    HANG INT NOT NULL,
    PRIMARY KEY (MACLB, NAM, VONG),
    FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB)
)
GO